### ISSUE TITLE
poppler-utils - pdftohtml issues while implementing in ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by dprasadk** [aperezdc/poppler#1]
Hi,

Please help me out in overcoming this issue, i have the same concern in windows too. So i thought of testing in Linux :

**Replication steps:**

1- I have saved this [image](https://datascience.blog.wzb.eu/wp-content/uploads/10/2017/02/ALA1934_RR-excerpt.pdf-3_1.png) - '' in my desktop and used img2pdf python package and finally converted it into pdf , please find below metadata for the converted pdf 

```
CreationDate:   Sun Nov 10 01:18:09 2019
ModDate:        Sun Nov 10 01:18:09 2019
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      2480 x 3505 pts
Page rot:       0
File size:      1449471 bytes
Optimized:      no
PDF version:    1.3
```

2- Then on top of it i ran `[ !cd data/ && pdftohtml -f 01 -c -xml demo02.pdf demo02.pdf.xml ]`
 i observed the below there was missing text XML tags  unable to extract text.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pdf2xml SYSTEM "pdf2xml.dtd">

<pdf2xml producer="poppler" version="0.41.0">
<page number="1" position="absolute" top="0" left="0" height="1257" width="889">
<image top="0" left="0" width="890" height="1258" src="demo02.pdf-1_1.png"/>
</page>
</pdf2xml>
```
3- i have tested the same code on this [pdf's ](https://github.com/WZBSocialScienceCenter/pdftabextract/blob/master/examples/catalogue_30s/data/ALA1934_RR-excerpt.pdf )its working , please find metadata for this pdf.

```
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          4
Encrypted:      no
Page size:      595.2 x 841.2 pts
Page rot:       0
File size:      470455 bytes
Optimized:      no
PDF version:    1.5
```

I have installed poppler by following this [link](https://www.howtoinstall.co/en/ubuntu/xenial/poppler-utils)

please find poppler-utils installed details 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
poppler-utils is already the newest version (0.41.0-0ubuntu1.14).
The following packages were automatically installed and are no longer required:
  linux-headers-4.8.0-36 linux-headers-4.8.0-36-generic linux-headers-4.8.0-41
  linux-headers-4.8.0-41-generic linux-image-4.8.0-36-generic
  linux-image-4.8.0-41-generic linux-image-extra-4.8.0-36-generic
  linux-image-extra-4.8.0-41-generic snap-confine
```

 
Kind Regards,
Durga

**Comment by aperezdc** [comment]
Hi @dprasadk! What your PDF has is an embedded image, which is a rectangle of pixels on a page so `pdftotext` does not have any way to know what the image contains. That's why you are not getting any textual output an the produced XML has instead an `<image>` tag.

If you want to analyze a bitmap image that contains text and obtain it as textual data what you will need is [OCR software](https://en.wikipedia.org/wiki/Optical_character_recognition) instead of Poppler. For example you could use [Tesseract](https://en.wikipedia.org/wiki/Tesseract_(software)).

I hope this helps!
