### ISSUE TITLE
pdf to html strange characters

### ISSUE THREAD

**Issue by pr4xx** [aperezdc/poppler#2]
Hey there! I am using pdftohtml successfully for different types of pdf files (mostly text, only few images).
However, I got a few files where the converted output seems to be "encrypted" and not readable, for example:
`fPkFKFbrFlgPCPHFPbkNPQbkimiKBbmGGNHLbPBkhKFlgF`

I tried different config options like -nodrm but with no success. The curious thing is, if I use pdftocairo and turn the file into an image, the output is just fine. It seems like the pdf can be parsed somehow.

Did you ever see a pdf file like this?

**Comment by aperezdc** [comment]
Sorry, this is *not* the main project page for Poppler. Please report bugs at https://gitlab.freedesktop.org/poppler/poppler/-/issues
